### ISSUE TITLE
QR-Rechnung

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#19]
To simplify the bank transfers we would like to suggest that after someone clicked on SEND PAYMENT INSTRUCTIONS a window pops up with the QR-Code. 

Is this something we could implement ourselves on our website? If yes, how?

Can you produce a QR-Rechnung with all the fields filled out, i.e. amount, address of token buyer and the unique reference number you generate and attach it to the email you send out? Otherwise we can do it. See my comment below.

![image](https://user-images.githubusercontent.com/47902312/151943394-ebecbaae-dd80-40b7-bfee-0a205f5b202c.png)

Generic QR-Code without amount, payee, and detailed reference.
![image](https://user-images.githubusercontent.com/47902312/151943511-6d35bcc9-c981-42a4-b0c7-17f00ea5adeb.png)

**Comment by luziusmeisser** [comment]
I would suggest to put the QR code into the email. That way, we have a verified email address and are sure that we can contact the sender of the money.

**Comment by Nicola8038** [comment]
I love this idea that I had myself many months ago. Not sure if you can
implement this yourself, but if you find a way to do it, even better.


--

Nicola Plain

CEO (ad interim)





Aktionariat AG

CHE-453.438.437

Mobile: +41 78 614 83 47

Email: ***@***.***

Web: https://aktionariat.com <http://aktionariat.com>



<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lw3rh45LM6yW1Lvd7b3T1MdDW49M7Pd1Gy6MB0&si=8000000020887941&pi=7ab7a5df-bc33-4db7-d231-ae22126fd614>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fQ47l4fGCmnW3Fbt5S3zcKScF43TBFPWrCS1&si=8000000020887941&pi=7ab7a5df-bc33-4db7-d231-ae22126fd614>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-4rCvX6W4hCVj23Fbt5SW3F7xMK41RjQSW36dwWw363mD8W3VWt0F4pmP_4W4fxxF_3C36GB0&si=8000000020887941&pi=7ab7a5df-bc33-4db7-d231-ae22126fd614>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fdJS31LdWZ2W3T1MdD49M7Pd0&si=8000000020887941&pi=7ab7a5df-bc33-4db7-d231-ae22126fd614>


*Aktionariat AG is a company founded by Murat Ögat & Luzius Meisser, a
Swiss Blockchain and Crypto Currency Pioneer. *

*Interested in blockchain? This article could be interesting for you: *Eine
Chance für den Finanzplatz | NZZ
<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-41_40qW3F7smG3K53ntW41S2r143TbcQW41Yx_n3JFWPWW43P1h_3QZmG8W1GzPSM3JF3YjW3zdYNr1GBdn5W49h9zp41n_LcW41PG6b45RjbMW4t3zhP1J7CLKW22WLHc49Kv7ZW3F6hB74fN0QQ0&si=8000000020887941&pi=7ab7a5df-bc33-4db7-d231-ae22126fd614>

**Comment by felivix** [comment]
I just reviewed the process with our ERP responsible and we can do it ourselves.
What we need from you is an email to our customer service with the order details and the address details of the token buyer.
Customer Service will then generate an invoice with the QR-Code and send it with our welcome letter per email to the investor.

The email that you send to the investor would confirm the purchase order and inform them that they will get from us an invoice with the QR-Code within a working day.

**Comment by Nicola8038** [comment]
Ok, that sounds good. We'll see how many investors will wait for the
QR-code and how many won't and pay immediately.

ok, wouldn't it be better to offer both options: paying with the bank
transfer information AND the QR-Code.

--

Nicola Plain

CEO (ad interim)





Aktionariat AG

CHE-453.438.437

Mobile: +41 78 614 83 47

Email: ***@***.***

Web: https://aktionariat.com <http://aktionariat.com>



<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lw3rh45LM6yW1Lvd7b3T1MdDW49M7Pd1Gy6MB0&si=8000000020887941&pi=0f3cf242-ab8f-4ebb-c427-15b9b9da0039>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fQ47l4fGCmnW3Fbt5S3zcKScF43TBFPWrCS1&si=8000000020887941&pi=0f3cf242-ab8f-4ebb-c427-15b9b9da0039>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-4rCvX6W4hCVj23Fbt5SW3F7xMK41RjQSW36dwWw363mD8W3VWt0F4pmP_4W4fxxF_3C36GB0&si=8000000020887941&pi=0f3cf242-ab8f-4ebb-c427-15b9b9da0039>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fdJS31LdWZ2W3T1MdD49M7Pd0&si=8000000020887941&pi=0f3cf242-ab8f-4ebb-c427-15b9b9da0039>


*Aktionariat AG is a company founded by Murat Ögat & Luzius Meisser, a
Swiss Blockchain and Crypto Currency Pioneer. *

*Interested in blockchain? This article could be interesting for you: *Eine
Chance für den Finanzplatz | NZZ
<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-41_40qW3F7smG3K53ntW41S2r143TbcQW41Yx_n3JFWPWW43P1h_3QZmG8W1GzPSM3JF3YjW3zdYNr1GBdn5W49h9zp41n_LcW41PG6b45RjbMW4t3zhP1J7CLKW22WLHc49Kv7ZW3F6hB74fN0QQ0&si=8000000020887941&pi=0f3cf242-ab8f-4ebb-c427-15b9b9da0039>

**Comment by felivix** [comment]
For us it is better if we manage the process and issue the invoice from our accounting system. When the payment comes in, it will automatically be matched with the corresponding invoice. If no payment comes in, the system will generate a reminder after a pre-defined amount of time.
For it to function we need from Aktionariat the order details **and** the address details of the token buyer

**Comment by Nicola8038** [comment]
Let's have a video call about this in order to discuss the details.




--

Nicola Plain

CEO (ad interim)





Aktionariat AG

CHE-453.438.437

Mobile: +41 78 614 83 47

Email: ***@***.***

Web: https://aktionariat.com <http://aktionariat.com>



<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lw3rh45LM6yW1Lvd7b3T1MdDW49M7Pd1Gy6MB0&si=8000000020887941&pi=75aac2e7-bf90-44de-8c0f-f96edaafc46b>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fQ47l4fGCmnW3Fbt5S3zcKScF43TBFPWrCS1&si=8000000020887941&pi=75aac2e7-bf90-44de-8c0f-f96edaafc46b>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-4rCvX6W4hCVj23Fbt5SW3F7xMK41RjQSW36dwWw363mD8W3VWt0F4pmP_4W4fxxF_3C36GB0&si=8000000020887941&pi=75aac2e7-bf90-44de-8c0f-f96edaafc46b>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fdJS31LdWZ2W3T1MdD49M7Pd0&si=8000000020887941&pi=75aac2e7-bf90-44de-8c0f-f96edaafc46b>


*Aktionariat AG is a company founded by Murat Ögat & Luzius Meisser, a
Swiss Blockchain and Crypto Currency Pioneer. *

*Interested in blockchain? This article could be interesting for you: *Eine
Chance für den Finanzplatz | NZZ
<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-41_40qW3F7smG3K53ntW41S2r143TbcQW41Yx_n3JFWPWW43P1h_3QZmG8W1GzPSM3JF3YjW3zdYNr1GBdn5W49h9zp41n_LcW41PG6b45RjbMW4t3zhP1J7CLKW22WLHc49Kv7ZW3F6hB74fN0QQ0&si=8000000020887941&pi=75aac2e7-bf90-44de-8c0f-f96edaafc46b>

**Comment by muratogat** [comment]
For reference, here is a list of websites that allow creating the QR Code
https://www.paymentstandards.ch/en/home/readiness/generators.html

This one is particularly interesting and detailed:
https://qr-rechnung.net/#/

However, none of them seem to provide an API. So I found the following Java library that seems up-to-date:
https://github.com/manuelbl/SwissQRBill

Please check if it is usable in our backend.
Two points to pay attention to:

- Is the debtor field optional? Because at this point we're not sure we know payer details
- Can a PDF be temporarily exported that can be attached to the existing payment request email we are already sending. Ideally we shouldn't store those PDF's somewhere. Can we even send a custom attachment with such emails?

Note that in the last discussion, we agreed on not to modify the existing email, but just adding the file as an attachment.
Perhaps we could add a sentence to indicate "Use the attached QR-Bill to easily pay." etc, but the payment information already displayed in the email will still be kept as it.

**Comment by felivix** [comment]
Any updates?

**Comment by KostasZav** [comment]
> Any updates?

Hi @felivix 

We have added this in our backlog labeled as prio 2 and expect to have this implemented by end of Q2 2023. 

https://github.com/aktionariat/backend/issues/712

**Comment by KostasZav** [comment]
Hi @felivix 

We wanted to let you know that we introduced a QR bill PDF attachment in the payment instructions email. Please have a look into the attached Sample PDF. We consider to add this QR in the last page of the brokerbot too (buy side flow) when buying shares with bank transfer but this might take us some time.

The information that we pass on this PDF:
- Amount
- IBAN and details of the company
- Investors Data
- Currency
- Message to the recipient of the payment. This is actually the reference code which is created after the completion of the action in the Brokerbot (i.e. VEDA - 123456).

Last but not least, since we introduced this QR bill PDF, we have eliminated your static QR from this email which was shared in this ticket as we believe it seems to be redundant.

Please let us know if you have any questions.

If not, I believe we can close this ticket.

[QRBill_DEXA-149051.pdf](https://github.com/aktionariat/reports/files/11063453/QRBill_DEXA-149051.pdf)

**Comment by felivix** [comment]
Great, thank you!
