### ISSUE TITLE
Dividends and reimbursements

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#20]
What are you recommendations regarding
1) paying-out dividends
2) reimbursing excess funds not required for the purchase of tokens (e.g. someone transferred CHF 2'800 for 100 tokens, however the bank deducted CHF 10 in fees and therefore only 99 tokens can be issued and the remaining CHF 18 need to be sent back to the token holder)?
Should we use XCHF for these payments? Or should we require them to provide their banking information when they register?

**Comment by Nicola8038** [comment]
We are currently working on an airdrop feature that can be used for both
purposes. Since the wallet address I known it might be easier for you to
reimburse using cryptofrancs.

--

Nicola Plain

CEO (ad interim)





Aktionariat AG

CHE-453.438.437

Mobile: +41 78 614 83 47

Email: ***@***.***

Web: https://aktionariat.com <http://aktionariat.com>



<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lw3rh45LM6yW1Lvd7b3T1MdDW49M7Pd1Gy6MB0&si=8000000020887941&pi=e7752ae4-1673-41a2-c657-293b0e1cc19d>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fQ47l4fGCmnW3Fbt5S3zcKScF43TBFPWrCS1&si=8000000020887941&pi=e7752ae4-1673-41a2-c657-293b0e1cc19d>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-4rCvX6W4hCVj23Fbt5SW3F7xMK41RjQSW36dwWw363mD8W3VWt0F4pmP_4W4fxxF_3C36GB0&si=8000000020887941&pi=e7752ae4-1673-41a2-c657-293b0e1cc19d>

<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4fdJS31LdWZ2W3T1MdD49M7Pd0&si=8000000020887941&pi=e7752ae4-1673-41a2-c657-293b0e1cc19d>


*Aktionariat AG is a company founded by Murat Ögat & Luzius Meisser, a
Swiss Blockchain and Crypto Currency Pioneer. *

*Interested in blockchain? This article could be interesting for you: *Eine
Chance für den Finanzplatz | NZZ
<https://t.sidekickopen06-eu1.com/s3t/c/5/f18dQhb0S7kC8fD6XKW5dK2qR2zGCz1N5xLs7slrBrYW1S-5-y3djZr_N5F2kFW3Zpn7f1CyYXb02?te=W3R5hFj4cm2zwW4mKLS-41_40qW3F7smG3K53ntW41S2r143TbcQW41Yx_n3JFWPWW43P1h_3QZmG8W1GzPSM3JF3YjW3zdYNr1GBdn5W49h9zp41n_LcW41PG6b45RjbMW4t3zhP1J7CLKW22WLHc49Kv7ZW3F6hB74fN0QQ0&si=8000000020887941&pi=e7752ae4-1673-41a2-c657-293b0e1cc19d>

**Comment by KostasZav** [comment]
Hi Felix,

Just an update on the dividends payment question. We are now able to technically support the payment of the dividends through the dashboard using the multisig address as a source address which actually means that it is only possible to distribute tokens from multisig to any addresses of your choice. It is up to the company to decide if the dividends payment will be done in a form of shares distribution or any other token distribution (maybe @luziusmeisser @muratogat a/o @Nicola8038 know more on that)

There are 2 steps to follow in general:

1) You need to create an allowance proposal to enable distributing tokens from the multisig address (this needs to be done only once) and then sign it.
2) Make use of the prefill table and go for the "all shareholders" option. Define the amount of tokens/share and create a proposal. Once signed, the shareholders will receive the tokens. 

Please note that you can manually amend the target addresses list if needed and the way described above is 1 of the many options that you have. By far I'd say the easier from a user perspective though (alternatively you will need to add the addresses manually or import an excel but personally I don't find the reason to go for it as it can be time consuming) 

I am attaching a few screenshots to guide you through and please feel free to let me know if you have any questions.

![1](https://user-images.githubusercontent.com/100678008/163202572-5817f51d-6591-44bf-bc8a-bcae88a3e88d.png)
![2](https://user-images.githubusercontent.com/100678008/163202597-a3c6a956-4860-4702-8c4b-732d564b1c60.png)
![3](https://user-images.githubusercontent.com/100678008/163202613-c8224672-fadd-4409-a23e-f03ab35868be.png)
![4](https://user-images.githubusercontent.com/100678008/163202641-6ebde408-9612-4138-8a5d-d00811b5194e.png)

If there are no further questions, I guess we can close this issue.

**Comment by felivix** [comment]
All looks good, except one first must transfer some XCHF or Tokens to the multisig address. 
Why can't we use the "Market for the VEDA token" address, where we have XCHF and VEDA token to distribute them?

![image](https://user-images.githubusercontent.com/47902312/163438997-e40728b6-2208-4b32-927f-80dca33b37dc.png)

![image](https://user-images.githubusercontent.com/47902312/163439095-124fb669-9e4a-4257-a974-48ebc25586b9.png)

**Comment by muratogat** [comment]
Hi Felix,
Although this is in our backlog, it can take some time and I don't have a specific release date for now.
Even when it's ready, the Brokerbot will need to support it and an update may be necessary.
I would suggest simply using "Reserves->Withdraw" section in the Brokerbot tab in the dashboard to transfer the necessary funds to the multisig first.
Once the funds are on the multisig address, you will be able to distribute them.
Thanks.

**Comment by luziusmeisser** [comment]
If we want to enable paying dividends directly from the brokerbot, we would need to adjust the smart contracts, either that of the Brokerbot or that of the Paymenthub.

**Comment by muratogat** [comment]
I would suggest to simply use "Reserves->Transfer" option in the Brokerbot tab first, to move the funds from the Brokerbot to the Multisig. Then the airdrop feature could be used as is.
As Luzius said, an update to the smart contracts would be necessary to allow a direct distribution from the Brokerbot.
I see the one step gain in usability, nevertheless I would prefer keeping the Brokerbot reserves for buying/selling. Sending the airdrop from the multisig would be simpler and clearer in terms of event logs.

**Comment by felivix** [comment]
Thank you @muratogat and @luziusmeisser for your explanations and suggestions.
It is good to have this feature, and transferring first some funds to the multisig is OK.
