### ISSUE TITLE
New Widget Investor Group

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#23]
Can you make the informative graphic of the Investor Group available as a widget?

![image](https://user-images.githubusercontent.com/47902312/154059843-75252bbe-7a98-4cc7-af68-5f5d66d7de7d.png)

**Comment by felivix** [comment]
This graphics has disappeared from the dashboard - and we wanted it also as a widget for our website ..... :(

**Comment by KostasZav** [comment]
Dear Felix,

Thanks a lot for your message. As you might have seen we are working on an overview page (landing page for the dashboard) and the shareholder group widget is a work in progress item. We plan to add it soon in the overview page, stay tuned.

Regarding the point of having this shareholder group widget uploaded/integrated on your website, the answer is yes. It has been meticulously designed and developed to cater for dashboard as well as website needs. 

Thank you for your patience and we always appreciate your feedback.

Best,
Kostas

**Comment by KostasZav** [comment]
Dear @felivix,

We are happy to let you know that the investor groups widget is now ready both in the overview page of the dashboard as well as a website widget.

For the integration of the widget on your website please click here --> https://hub.aktionariat.com/widgets/?token=VEDA . The widget is available in both english and german language. In order to embed it in your webpage, you will need to copy and paste the code which can be found when you click view code. Based on a separate email question about the configuration of the widget, I want to let you know that the widget can't be scaled and therefore can't be enlarged in order to fit with the remaining blocks on your website.

If there are no further questions or remarks, we can close this issue.

**Comment by KostasZav** [comment]
Closing this issue since it is in PROD.
