### ISSUE TITLE
Historic Market Price Widget

### ISSUE THREAD

**Issue by felivix** [aktionariat/reports#7]
Wie können wir die Ansichten für 1, 3, 6 Monate und 1 Jahr aktivieren?

![image](https://user-images.githubusercontent.com/47902312/149631740-137176b2-eeaa-496c-bf64-0ee52ea44de8.png)

**Comment by muratogat** [comment]
They are disabled because of lack of data points. Once there is enough data, they will become automatically activated.
What we could do is to hide them if there is not enough data.
@luziusmeisser @bladekp currently only 2 data points are retrieved from the /prices api:
[[1629493686300,20.0], [1642339595093,28.0]]
Hence a single line. 1m and 3m would be just points. 6m 1y would be the same as "All". That's why our chart library is disabling them.

**Comment by bladekp** [comment]
So I think this is working fine, anything to do here?
